# Generated by Django 5.1 on 2024-09-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='trackinghistory',
            name='remaining_balance',
        ),
        migrations.RemoveField(
            model_name='trackinghistory',
            name='expense',
        ),
        migrations.DeleteModel(
            name='RemainingBalance',
        ),
        migrations.DeleteModel(
            name='TrackingHistory',
        ),
    ]
