# Generated by Django 5.1 on 2024-09-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_userincome_remove_trackinghistory_remaining_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userincome',
            name='income',
            field=models.IntegerField(),
        ),
    ]
