# Generated by Django 5.1 on 2024-09-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_expense_amount_alter_userincome_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userincome',
            name='income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
