# Generated by Django 5.1 on 2024-09-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
    ]
